apiVersion: v1
kind: Service
metadata:
  name: postgresql-lb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql-ha
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
